// <auto-generated />
using System;
using Forums.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forums.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130111836_MigationTwo")]
    partial class MigationTwo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forums.API.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("359e8684-ea02-41b2-b2a7-e2328ff59cfc"),
                            CommentDate = new DateTime(2026, 1, 31, 15, 18, 36, 492, DateTimeKind.Local).AddTicks(9732),
                            Content = "This is the content of the first COMENT.",
                            TopicId = new Guid("7bef7d61-bd07-4bd4-b751-750e2a49c5d7")
                        },
                        new
                        {
                            Id = new Guid("83556f70-60f4-41b1-bc5a-d69bedf5b277"),
                            CommentDate = new DateTime(2026, 2, 1, 15, 18, 36, 492, DateTimeKind.Local).AddTicks(9738),
                            Content = "This is the content of the SECOND COMENT.",
                            TopicId = new Guid("d992b1b9-3548-4311-a31c-e6a802865c6a")
                        });
                });

            modelBuilder.Entity("Forums.API.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CommentsAreAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("Date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastCommentDate")
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bef7d61-bd07-4bd4-b751-750e2a49c5d7"),
                            CommentsAreAllowed = true,
                            Content = "This is the content of the first topic.",
                            CreatedDate = new DateTime(2026, 1, 30, 15, 18, 36, 492, DateTimeKind.Local).AddTicks(9641),
                            LastCommentDate = new DateTime(2026, 1, 30, 15, 18, 36, 492, DateTimeKind.Local).AddTicks(9643),
                            Title = "First Topic"
                        },
                        new
                        {
                            Id = new Guid("d992b1b9-3548-4311-a31c-e6a802865c6a"),
                            CommentsAreAllowed = true,
                            Content = "This is the content of the second topic.",
                            CreatedDate = new DateTime(2026, 1, 30, 15, 18, 36, 492, DateTimeKind.Local).AddTicks(9645),
                            LastCommentDate = new DateTime(2026, 1, 30, 15, 18, 36, 492, DateTimeKind.Local).AddTicks(9646),
                            Title = "Second Topic"
                        },
                        new
                        {
                            Id = new Guid("29738ebb-795a-4175-be6d-7804d7da6acc"),
                            CommentsAreAllowed = true,
                            Content = "This is the content of the third topic.",
                            CreatedDate = new DateTime(2026, 1, 30, 15, 18, 36, 492, DateTimeKind.Local).AddTicks(9647),
                            LastCommentDate = new DateTime(2026, 1, 30, 15, 18, 36, 492, DateTimeKind.Local).AddTicks(9648),
                            Title = "Third Topic"
                        });
                });

            modelBuilder.Entity("Forums.API.Entities.Comment", b =>
                {
                    b.HasOne("Forums.API.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
