// <auto-generated />
using System;
using Forums.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forums.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202091601_Namefour")]
    partial class Namefour
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forums.API.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8aac92c-411a-4b8e-af15-8cb9a70e7044"),
                            CommentDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "This is the content of the first COMENT.",
                            TopicId = new Guid("1c03c62e-b299-483a-ac61-cfa2fa0878c9")
                        },
                        new
                        {
                            Id = new Guid("c5bd2734-c5ba-4928-994b-12260cac0297"),
                            CommentDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "This is the content of the SECOND COMENT.",
                            TopicId = new Guid("1ae2f862-c948-458e-88dd-b1ac4e047648")
                        });
                });

            modelBuilder.Entity("Forums.API.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CommentsAreAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("Date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastCommentDate")
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c03c62e-b299-483a-ac61-cfa2fa0878c9"),
                            CommentsAreAllowed = true,
                            Content = "This is the content of the first topic.",
                            CreatedDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastCommentDate = new DateTime(2026, 2, 2, 13, 16, 0, 722, DateTimeKind.Local).AddTicks(2271),
                            Title = "First Topic"
                        },
                        new
                        {
                            Id = new Guid("1ae2f862-c948-458e-88dd-b1ac4e047648"),
                            CommentsAreAllowed = true,
                            Content = "This is the content of the second topic.",
                            CreatedDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastCommentDate = new DateTime(2026, 2, 2, 13, 16, 0, 722, DateTimeKind.Local).AddTicks(2273),
                            Title = "Second Topic"
                        },
                        new
                        {
                            Id = new Guid("922477dc-b396-439d-aefa-8a251a671c43"),
                            CommentsAreAllowed = true,
                            Content = "This is the content of the third topic.",
                            CreatedDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastCommentDate = new DateTime(2026, 2, 2, 13, 16, 0, 722, DateTimeKind.Local).AddTicks(2275),
                            Title = "Third Topic"
                        });
                });

            modelBuilder.Entity("Forums.API.Entities.Comment", b =>
                {
                    b.HasOne("Forums.API.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
